name: K-Populators
version: '1.0'
main: org.nxdus.populators.MainPaper
api-version: '1.20'

commands:
  populates:
    description: "K-Populates"
    permission: "populates.admin"
    aliases:
      - realm

depend:
  - Oraxen